version: "3"

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - portfolio_node:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_node

  backend:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: portfolio_node
      NODE_ENV: local
    depends_on:
      - db

volumes:
  portfolio_node:
